name = "Database Test"

users = [
  { name = "John Doe", age = 30, active = true, scores = [85, 92, 78] },
  { name = "Jane Doe", age = 25, active = false, scores = [95, 88, 90] },
  { name = "Peter Jones", age = 40, active = true, scores = [70, 80, 75] }
]
